set_power_limit:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: occp
    limit_w:
      required: true
      selector:
        number:
          min: 0.01
          unit_of_measurement: "W"
          mode: box
    phases:
      required: false
      selector:
        select:
          options: ["1", "2", "3"]

clear_power_limit:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: occp

authorize_id_token:
  fields:
    charge_point_id:
      required: true
      selector:
        text:
    id_token:
      required: true
      selector:
        text:
    device_id:
      required: false
      selector:
        device:
          integration: occp

reset:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: occp
    reset_type:
      required: true
      selector:
        select:
          options: ["Soft", "Hard"]

unlock_connector:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: occp

get_configuration:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: occp
    keys:
      required: false
      selector:
        text:
          multiple: true

change_configuration:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: occp
    key:
      required: true
      selector:
        text:
    value:
      required: true
      selector:
        text:
