set_power_limit:
  target:
    device:
      integration: occp
  fields:
    limit_w:
      required: true
      selector:
        number:
          min: 0.01
          unit_of_measurement: "W"
          mode: box
    phases:
      required: false
      selector:
        select:
          options: ["1", "2", "3"]

clear_power_limit:
  target:
    device:
      integration: occp

authorize_id_token:
  fields:
    charge_point_id:
      required: true
      selector:
        text:
    id_token:
      required: true
      selector:
        text:
